### ISSUE TITLE
use akka restartflow

### ISSUE THREAD

**Issue by schmitch** [schmitch/akka-pg#1]
It would be useful to use https://github.com/akka/akka/pull/23367 once merged

**Comment by ktoso** [comment]
Akka 2.5.4 is released with those stages

**Comment by schmitch** [comment]
thanks ;)

**Comment by schmitch** [comment]
Closed with https://github.com/schmitch/akka-pg/commit/603c72f7c18d2dbcf09753d88b086029b4a80932
